  $(function() {
    var availableTags = [

"Tarun”,”Agarwal",
“Alamance County Dental Clinic" /*,
"Alex”,”Alexander",
"Paul Charlotte”,”Alexander",
"Hani”,”Aboufoul",
"Gregory”,”Abrams",
"Smoak”,”Ackerman",
"Craig Q.”,”Adams",
"Vincent”,”Allison",
"Jerry”,”Alvis",
"Michael”,”Anderson",
“Anderson Creek Dental Clinic",
"Daniel”,”Makely",
"Mary”,”Makhlouf",
"Frank”,”Maness",
“Piedmont Health Services”,”Moncure”,
“Piedmont Health Services”,”Prospect Hill”,
"Stephen”,”Pieroni",
"Amy sold to Bremer”,”Piersma",
"Paul”,”Scruggs",
"Mark”,”Scurria",
"Debra”,”Seaton",
"John”,”Cordes",
“Twin County Rural Health Center”,”Hollister”,
“First Choice Community Health Centers",
“Perentis & Perentis”,”Atlantis”,
“Wake Technical Community College",
"Joe K.”,”Harris",
"Richard and Amy”,”Hunt",
"Larry”,”Moray”,”Cary”,
"Howard”,”Yee”,”Roanoke Rapids”,
“Pearson, Jefferson and Camp”,”Raleigh Oral Surgery”,
"Donald”,”Hardee",
"Robert”,”Kulp",
"Roslyn”,”Crisp",
"Carl Meritt”,”Steger",
"Ben and Susan”,”Thompson",
“Goshen Medical Center",
"Steven B.”,”Andreaus",
"Mark J.”,”Andrews, DDS, PA",
"Prince”,”Arrington”,”The Creative Smile Center”,
"Kevin”,”Arthur",
"Angela”,”Ruff",
"Kevin”,”Atkins",
“AVAILABLE",
"Edward Stevenson”,”Bailey",
"Howard”,”Baker",
"Steven”,”Baker",
"Whitney”,”Bales & Dr. Susan Simpson",
"Ann”,”Banes",
"Jeffrey”,”Banks",
"Richard”,”Barbaro",
"Robert”,”Barham",
"Bruce S.”,”Barker & Dr. Walter Rohner",
"Joseph”,”Barker",
"Tim”,”Barlow",
"Karen”,”Barwick",
"Michael”,”Bass",
"Arash”,”Bassiri”,”Owen Drive”,
"Richard”,”Bateman",
"Amy”,”Batten",
"Laura”,”Wellener",
"Gary”,”Beavers",
"Paul”,”Beavers",
"Wayne”,”Beavers",
"Gary”,”Behrend",
"Thomas”,”Bell",
"Jeffrey”,”Bell",
"Barry”,”Belton & Dr. Kevin Schrimper",
"Randal”,”Benefield",
"John”,”Berry",
"Gloria”,”Berry Holly",
"Raj”,”Bhagwandass",
"Shamsi”,”Bhanji",
"Michael K.”,”Bielinski",
"Geri”,”Bills",
"Jessica”,”Bishop",
"Ken”,”Black",
"Bill”,”Blaylock",
"Brent”,”Blaylock",
"James”,”Boggs",
"Alex”,”Bollendorf",
"Mike”,”Bolus",
"Larry”,”Booth",
"Sue”,”Borgschulze",
"Mark”,”Bostic",
"Chris”,”Bouldin",
"John”,”Bradsher",
"Nona”,”Breeland",
"Lionel”,”Nelson",
"Karen”,”Bremer",
"Erich”,”Brewer",
"L. Samuel”,”Bright",
"Beverly”,”Broadwell",
"Greg”,”Brooks",
"Thomas C.”,”Steet",
"Andy”,”Brown”,”retired”,
"Kenneth”,”Brown",
"Marshall”,”Brown",
"Michelle”,”Brown",
"William”,”Brown",
"Karen”,”Bruggers",
"William”,”Brunk",
"Gary”,”Bryan",
"Susan”,”Buckland",
"James E.”,”Buckthal",
"Eric”,”Bufano & Dr. Lisa Bufano",
"Charles”,”Burnham",
"Felecia”,”Burridge",
"Robert”,”Burroughs",
"David A.”,”Burton",
"Joe”,”Butler",
"Charles”,”Byerly",
"Jeff”,”Calamos & Dr. Patrick Marsh",
"Jeff”,”Calamos & Dr. Patrick Marsh”,”West”,
"C.K.”,”Caldwell",
"Michael”,”Caporal",
"Robert”,”Capps and Dr. Mark Bowman",
"Rex”,”Card",
"Steve”,”Card",
“Wake Med",
“Carolina Pines Community Health Center",
"Cheryl T.”,”Carraway",
"Charles”,”Casher",
“Cassidy & Orlowski",
"Pat”,”Cassidy & Partners PLLC",
"Mark”,”Castor",
"Joseph”,”Catlett",
"Jeffrey”,”Cecil",
"Laura”,”Chamberlain",
"Quyen”,”Chang",
"Sam”,”Chang",
"Ray”,”Chavis",
"Michael”,”Cherry",
"Mike W.”,”Choe”,”Westlake Family Dentistry”,
"John”,”Christensen",
"Lam”,”Chu",
"James J.”,”Chun",
"Martin V.”,”Clark",
"W. Christopher”,”Claypoole",
"W. Christopher Sold to Ghodrat”,”Claypoole & Associates",
"Edward”,”Clemons",
"Thomas”,”Clifton",
"Robert”,”Cloninger",
"Sharon”,”Cobham”,”Garner”,
"Sharon”,”Cobham & Associates”,”North Hills  Dental Care”,
"Paula”,”Coffey",
"Stephen”,”Coker",
"Andrew”,”Collins",
"James”,”Colson",
"Clifford”,”Compton",
"Crystal”,”Finnegan",
"Teresa”,”Conley",
"Richard”,”Cooke",
"Thomas”,”Cooke",
"Javon”,”Cooper",
"Velma”,”Cooper",
"Richard”,”Patterson",
"David”,”Cotty",
"Joseph”,”Cowart",
"Mason O.”,”Cox & Dr. Michael Schroer",
"Jay”,”Coyle & Associates",
"Buckley”,”Cozart",
"W.S.”,”Cozart",
"Ned”,”Craft",
“Craven County Health Department",
"Brent”,”Crawford",
"Richard”,”Cray",
"Timothy”,”Creech",
"Kenneth”,”Marsh",
"Lynette”,”Crocker",
"Ray”,”Cross",
"Keith”,”Crouch",
"Lee”,”Currin",
"Kathy L.”,”Davies",
"Gwyn”,”Davis & Associates",
"Keisha B.”,”Davis DDS PA",
"Mike”,”Dearstyne",
"Matthew”,”Delbridge",
“Delta Dental Plan of N.C.",
"sold to Dr. Phillip Lisk”,”Dengler",
"Bernard J.”,”Dennison, Jr.",
"Vinay”,”Chirnalli",
“Smiles of America”,”Cary”,
"Louis G.”,”Spelios, DMD, PA”,”Garner”,
“Smiles of America”,”Lake Boone”,
“Smiles of America”,”Lynn Road”,
“Smiles of America”,”Corporate”,
“Dental Works”,”Cary #108”,
“Dental Works”,”Durham #105”,
"Kent”,”Denton",
“Dest, Faulk & Kye”,”First Union”,
“Dest, Faulk & Kye”,”Main”,
"Joe”,”Devlin",
"David”,”Dickerhoff”,”Sspring Lake Dental Group”,
"Gary”,”Dilley",
"Harold”,”Dixon",
"Marilee”,”Dixon & Dr. Suzanne Holmes",
"David”,”Dobson",
"Scott”,”Donner",
"H.E.”,”Douglas",
"Claude”,”Dowd",
"Julian”,”Drew",
"Thomas”,”Drew",
"Hoang”,”Drouin",
"Catherine”,”Duckworth-Bickley",
“Duke Medical Center",
“Duke University Medical Center”,”PA325054”,
"Beth”,”Dunsmoor",
“Duplin County Health Department",
“Durham County Health Department",
"Sharon”,”Cobham”,”Durham Family Dental Care”,
"James”,”Eaker",
"Scott”,”Earp",
“Edgecombe Health Department",
“Edrington & Edrington",
"Tracy”,”Edwards",
“Eggleston",
"Cynthia”,”Elderkin",
"Robert”,”Elliott”,”Cary Pediatric Dentistry”,
"Dennis”,”Ellis",
"Robert A.”,”Englehardt & Dr. Bruce A. Vande Berg",
"Todd”,”Engstrom",
"Scott”,”Erickson",
"Catherine”,”Evans",
"Christopher”,”Faucette",
"R. Kelly”,”Faulk",
“FDN",
"Ray”,”Ferri & Dr. Patrick Lawrence",
"Charles”,”Ferzli”,”Kildaire Farm”,
"Gregg”,”Festa",
"J. David”,”Fisher",
"William H.”,”Fitts",
"Michael”,”Fleming",
"Stanley”,”Fleming",
"Hal”,”Fogleman",
"Renee”,”Foley",
"Stan”,”Ford",
"Donald R.”,”Fortner",
"Leon”,”Fowler, Jr.",
"Jodi Hamilton”,”Foy",
“Franklin County Health Department",
"Robert”,”Freedland",
"Donn B.”,”Freeman",
"David”,”Freshwater & Dr. Fred Howdy",
"James H.”,”Fryar III",
"R.”,”Fuller III & Dr, R. Fuller IV",
"Carl”,”Furr",
"Roy E.”,”Gaines, Jr.",
"Mary”,”Duffy",
"Joseph”,”Gatewood",
"Christine”,”Gatti",
"Elisabeth”,”Gerics",
"Hushang”,”Ghodrat”,”Ruin Creek”,
"Michael”,”Givens",
"Timothy W.”,”Godsey",
"Lynn”,”Godwin”,”Godwin Family Dentistry”,
"Anna”,”Goodrich",
"Ernest”,”Goodson",
"Lewis”,”Goodwin",
"Michael”,”Gordon",
"William”,”Gordon",
"David”,”Gover & Dr. Susan Gover",
"Robert”,”Gray",
“Greene County Health Care",
"David”,”Greenlee",
"Laura”,”Grier",
"Tim”,”Grinder",
"Jerald”,”Grotstein",
"Matthew”,”Bereman",
"Chris”,”Gudger",
"Lisa”,”Gushin",
"Catherine”,”Ha & Dr. Robert Ha”,”Cary”,
"Catherine”,”Ha & Dr. Robert Ha”,”Durham”,
"Diane”,”Habrel",
"Stephanie”,”Hackney",
"David”,”Hall”,”Cary”,
"David J.”,”Hall, Jr.",
"John”,”Hall",
"Linda”,”Hall & Dr. David Snyder",
“Hall, Parker & McDaniel",
"Mike P.”,”Hamby",
"Sean”,”Hamilton",
"Steve”,”Hamrick”,”Raleigh Periodontics”,
"H.H.”,”Hancock",
"Ilias”,”Haralambakis",
"W. Stan”,”Hardesty",
"Jim”,”Harding",
"Cheryl”,”Hardison",
"James”,”Hardy",
"Gearld”,”Hargis",
"Charles”,”Harless sold pratice do not send card",
"John”,”HarmanDo not send card",
"Sharon”,”Harrell",
"Daniel”,”Harris",
"Michael”,”Harrison",
"James”,”Harrold”,”Sunset”,
"James”,”Harrold”,”Oakwood”,
"David”,”Harsant",
"James C.”,”Hart",
"Steve”,”Hart",
"Chris”,”Hartung",
"Michael”,”Hattaway",
"C. Ryan”,”Haygood",
"Kent”,”Healey",
"Janice”,”Heard",
"J.”,”Hedgecoe & Dr. D. Hedgecoe",
"Mark”,”Helms",
“Henderson and Henderson",
"Regina”,”Henderson-Jordan",
"Robert”,”Hermann",
"T.C.”,”Hesmer",
"Lenonard”,”Hess",
"Stuart”,”Higgins",
"Brian Charlotte”,”Hill",
"Mark”,”Hill",
"Williard”,”Hinnant & Dr. Keith Hinnant",
"Carol”,”Hipps",
"Hana”,”Hobbs",
"Oliver”,”Hodge",
“Hoffman, Jordan, Turner & Butler",
"Richard”,”Hogan",
"James”,”Hoke",
"F. T.”,”Holcher",
"Michael”,”Holesh",
"C. W.”,”Holland",
"Gene”,”Holland",
"Jane”,”Holt",
"Richard”,”Holzbach do not send card",
"Ronald”,”Honeycutt",
"Wallace”,”Honeycutt (no christmas card)",
"Paul”,”Hood",
"G.R.”,”Horton",
“Pretzer & Kornstein”,”Wake Pediatric Dentistry”,
"Diane”,”Hourigan",
“Howarth Family Dental Center”,”Raleigh”,
“Howarth Family Dental Center",
"Eugene”,”Howden",
"Larry”,”Howell",
"Wilson”,”Hoyle",
"H.H.”,”Hughes",
"Scott”,”Hum",
"Armin”,”Abron",
"Mark”,”Hunt”,”“,
"Luther”,”Hunter",
"Beth”,”Grooms",
"Barbara”,”Hutcherson",
"Luther”,”Hutchins",
"W. Thomas”,”Hutchins",
"Nedda”,”Ibrahim",
"Jeffrey”,”Iglhaut",
"Anthony”,”Immediata",
“Intermed",
“Iredell County Health Department",
"John”,”Iseman",
"David”,”Jackson",
"Dorothy”,”Jacobyansky",
"Kathy moved to Charolotte”,”Jakuc",
"Candice”,”Arrick and Associates",
"Stephanie”,”Jenkins",
"P.W.”,”Jessup",
"Douglas”,”Jewson",
“John Umstead State Hospital",
"Elbert”,”Johnson",
"Mark”,”Johnson",
"Gary”,”Jones",
"Mark A.”,”Jones",
"Michael T.”,”Jones”,”Cary”,
"Michael T.”,”Jones”,”Raleigh”,
"Todd”,”Jordan",
"Paul”,”Kazmer, Jr.",
"M.A.”,”Kazmian",
"Jeff”,”Kearney",
"Martha Ann”,”Keels",
"Brian”,”Kelleher",
"Burt”,”Kelling",
"R. William”,”Kelly",
"Thomas V.”,”Kelly",
"Jeff”,”Kennedy",
“Kent",
"Raymond”,”Kessler III",
"Fred”,”Keyser, III",
"Chris”,”Kibler",
"William”,”Kincaid & Dr. Deborah Kincaid",
"Wesley”,”King",
"W.H.”,”Kingery”,”Cross Creek Dental”,
"Darren”,”Koch",
"James”,”Kirk”,”SPRING LAKE DENTAL CENTER”,
"George”,”Kirkland",
"Richard”,”Kitchell",
"John”,”Kitzmiller”,”Apex Dental Group”,
"Vance”,”Knight",
"Winfield”,”Knight & Dr. Diane Nagel",
“Knight & Malek”,”Axiom of Big Oak”,
“Knowles, Smith & Associates”,”Corporate Office”,
"Kevin”,”Koebley",
"James”,”Koglin do not send card",
"Daniel”,”Kolzet",
"Michael”,”Kretchmer",
"David”,”Kuhn",
"Jennifer”,”Massey",
"Robert”,”Labusohr",
"David”,”Lambert",
"Larry”,”Moray”,”Raleigh”,
"Herbert”,”Land",
"Trent”,”Landenberger",
"David P.”,”Lane",
“Lane and Associates”,”Biscoe Office”,
“Lane and Associates”,”Fuquay Varina”,
“Lane and Associates”,”Lillington”,
"Joseph sold to Wagnor”,”Laton",
"Laszlo”,”Ledenyi",
"Cyrus F.”,”Lee",
"Folden”,”Lee",
"Susan”,”Lee",
"Tammy”,”Lee",
“Lee & Associates”,”Bent Tree”,
“Lee & Associates”,”Smithfield”,
“Lee County Health Department",
“Lee, Fussell, Humphreys & Humphreys",
"Bobby”,”Mallik",
"Thomas”,”Leech",
"Fred”,”Lehmann",
"Joseph”,”Lenard",
"Marcia L.”,”Lewis",
"William”,”Lewis",
"Lynn”,”Lewis & Dr. Todd Greeson",
"Sidney”,”Libfraind",
“Lincoln Community Health Department",
"William”,”Lind",
"Roland”,”Lingle",
"Lynn”,”Linville-Lauritano",
"Walter”,”Linville",
"Ellis”,”List",
"Danny”,”Lloyd",
"Slayter”,”Lloyd",
"Joel”,”Locke",
"Cheryl”,”Locklear",
"Charles”,”Lohr",
"Thomas”,”Long",
"William B.”,”Long",
"Teresa”,”Wooddell",
"Jeffrey”,”Love",
"Douglas”,”MacLeod",
"Harold”,”Madden & Dr. Susan Madden",
"Gerard”,”Magno",
"George”,”Mani",
"C. Ashley”,”Mann",
"Victor”,”Mann",
"Darrell”,”Mansfield",
"Joseph”,”Marchese",
"Chris”,”Martin",
"Sandra Elizabeth”,”Martin",
"Toni”,”Mascherin",
“Mashburn & Zsambeky",
"Fred T.”,”Ridge",
"Roy do not send  card”,”Massengill",
"Gentry”,”Matthews",
"Paul”,”Maus",
"Harold”,”Maxwell",
"Steven”,”Kizior",
"Greg”,”Mayes & Dr. Lisa Mayes",
"Trip”,”McClendon",
"Robert”,”McArthur",
"Darwin”,”McCaffity",
"Dana”,”McCall",
"Arnold”,”McClain",
"Jessica”,”McConnell”,”“,
"Lynette”,”McDonald",
"Roger”,”McDougal",
"Jamel”,”McDuffie",
"John”,”McGinty",
"Frank”,”McGrath",
"Bettie”,”McKaig",
"William”,”McKay",
"James”,”McKenzie",
"John L.”,”McKinnon",
"Kurt”,”McKissick",
"W. Carl”,”McMillan”,”Holistic Dental Center”,
"Knox”,”McMillan",
“Medicaid Dental Care",
"Scott A.”,”Menaker",
"Samuel”,”Mesaros # disconnected",
"Robert”,”Meyer",
"Gary”,”Michels",
"Kim”,”Miller",
"Clyde”,”Minges",
"James”,”Mitchell",
"W. Paul”,”Mitchum",
"Michael”,”Modlin",
"Kamron”,”Monroe & Dr. Clement Monroe",
"Wayne”,”Moore",
"Sean”,”Mooring",
"Rob”,”Moran”,”Waverly”,
"Larry”,”Moray”,”Ortho”,
"Dawn”,”Morehead”,”“,
"David”,”Moretz",
"Dawn”,”Moretz",
"Michael B.”,”Morgan",
"Walter”,”Morris",
"Jeff”,”Morrison",
"Michelle”,”Mottinger",
“MTW Health District",
"Michael”,”Muckler",
"Jack”,”Mullen",
"H.V.”,”Murray",
"John”,”Murrell",
“N.C. Department of Corrections”,”Central Prison”,
“N.C. Department of Corrections”,”Franklin”,
“N.C. Department of Corrections”,”Harnett”,
“N.C. Department of Corrections”,”Polk Center”,
“N.C. Deptartment of Corrections”,”Umstead”,
"Paresh”,”Naran",
"Kevin”,”Neshat",
“Net 32",
“Nguyen and Nguyen Dentistry Partnership”,”Gentle Family Dentistry”,
"Thomas P.”,”Niedermeier",
"Robert”,”Niles",
"Jeff”,”Noblett",
"Richard”,”Noel",
"Kenneth”,”Oakley sold office-no christmas card",
"Mark”,”Odom",
“Olcott Family Dentistry",
"James”,”Oldham",
"Robert L.”,”Orander",
“Orange County Health Department",
"Richard”,”Orlowski",
"Betty”,”Ostrow",
"Aaron”,”Troppmann",
"Desiree”,”Palmer",
"Harwell”,”Palmer",
"Robert”,”Pappert",
"Junhie”,”Park",
"Jim”,”Parker",
"Laura”,”Parra",
"Dicky”,”Parrish",
“Partnership for Children Pediatric Dental Clinic",
"Jinesh”,”Patel",
"Donald”,”Patrick",
“Oral Maxillofacial Surgery Associates”,”Durham”,
"Michael”,”Peele",
“Perentis & Perentis”,”Carousel”,
"Kenneth T.”,”Perkins",
"Larry”,”Perkins",
"Joseph”,”Perry",
"Randy”,”Perry",
"Bryan”,”Persinger",
“Person Family Dental Center",
"Daniel”,”Petrocella”,”New Hope Dental”,
"Thomas”,”Pezdek & Associates",
"Robert”,”Phillips",
“Piedmont Health Services”,”Chapel Hill”,
"Mark”,”Pike",
"Larosa”,”Pinnex-Bailey",
“Pitt County Health Department",
"Marvin”,”Pleasants",
"Kenneth”,”Podger",
"David G.”,”Polhemus DDS, PLLC",
"Jeff”,”Poore",
"Robert”,”Poteat",
“Rich, Smith, & Tart",
"John”,”Powell, Jr.",
"Brad”,”Pressley",
"Valerie”,”Preston",
"David”,”Price",
"Larry”,”Price",
"Carlos”,”Privette",
"Kim”,”Pryzgoda",
"James”,”Pyle",
"Naureen”,”Qazi",
"Joseph”,”Quigg",
"Matthew”,”Quinlivan",
"Robert”,”Quintano",
"Daniel”,”Radatti",
"James”,”Rafael",
"Alicia”,”Ramos",
"Ranjini”,”Pillai",
"Harry deceased”,”Ramsey",
"Sam”,”Randall",
"Stephen”,”Randall",
"Kirby”,”Ransom",
"Catherine”,”Ray",
"Larry do not send card”,”Ray",
"Margaret”,”Ray",
"Bobby”,”Raynor",
"Frank”,”Reade",
"Jerry”,”Rebrey",
"Jeff”,”Reintgen”,”Raleigh”,
"Marcia”,”Rementer",
"Alexander”,”Resnansky",
"Angie”,”Rhodes",
"Lisa”,”Ribaudo",
"Michael”,”Riccobene”,”Selma Office”,
"Roy”,”Richardson",
"Paul”,”Richmond",
"Michael”,”Richter",
"Meade”,”Ridge",
"Trent closed practice”,”Rigsbee",
"Lawrence”,”Rivers",
“Robeson Health Care Corporation",
"Theresa”,”Robinson",
"Harold”,”Rogers",
"Stanley”,”Rogers",
"Winslow”,”Rogers",
"Karen”,”Romine",
"Donald W.”,”Rose",
"Kyle J.”,”Roth”,”Greensboro”,
"Kyle J.”,”Roth”,”Harvest Oaks”,
"Kyle J.”,”Roth”,”Mobile”,
"Kyle J. sold to Dr. Koren”,”Roth”,”Smithfield”,
"Kyle J.”,”Roth”,”Wake Forest”,
"Richard”,”Runkle",
"Elizabeth”,”Rushin",
"Ron”,”Salem",
"E. Scott”,”Saltzman",
"Carlos”,”Sanchez",
"James”,”Sarantos & Dr. James Sarant",
"Phillip”,”Savage",
"Anita”,”Sawhney",
"Artemis”,”Scandalios",
"Douglas”,”Scarboro",
"Thomas”,”Schaaf",
"Kurt”,”Scheetz",
"Gary”,”Schlotterer”,”Digital Dentistry at Southpoin”,
"Rebecca”,”Schmorr",
"Susanne P.”,”Jackson",
"Arthur”,”Schramm",
"Jason”,”Cataldo",
"Curt”,”Schweitzer",
"Jim retired”,”Sconyers",
"Walter”,”Scott”,”Breezewood office”,
"T.”,”Sebastian & Dr. K. Spaulding",
"Larry”,”Seitlin & Dr. Ed Shapiro",
"Madeline”,”Serrano",
"Grant”,”Service",
"Tammy”,”Severt",
"Erun”,”Sharda",
"Howard”,”Shareff",
"Alex”,”Sharpless & Dr. Orlando Stovall",
"Chris”,”Sheaffer & Dr. Ben Brown",
"James”,”Shearer",
"Tina”,”Shih",
“Shoehill Family Dentistry- Dr. Dan Davis DMD",
"Thomas”,”Sholar",
"Ron”,”Short",
"Cheryl”,”Siegel",
"Jefferson”,”Sims",
"Macon”,”Singletary",
"Robert”,”Sink",
"Joseph”,”Skladany",
"John”,”Slaughter",
"Eldon”,”Sloan",
"Celeste”,”Sloop",
"Troysold  to Hourigan moved O.Banks”,”Sluder",
"Mandy”,”Ghaffarpour",
"Karl”,”Smith",
"Lynn”,”Smith",
"S. Owen”,”Smith",
"Wesley”,”Smith",
"Marcella”,”Sockwell",
"Sidney”,”Sockwell & Dr. Marcella Sockwell",
"Ronald”,”Spain",
"D. Reed”,”Spears & Dr. Bart Cleary",
"Harold”,”Speight",
"Alena”,”Spielberg",
"Robert”,”Stancill",
"Bobbi”,”Stanley",
“Stedman Family Dental Center",
“Stedman Wade Health Services",
"Spiegler”,”Stephen",
"Mark”,”Stephenson",
"Paul W.”,”Stewart",
"Randall”,”Stewart",
"William”,”Stoppelbein & Dr. Dexter Coleman",
"Michael L.”,”Stout",
"Rick”,”Stovall",
"Sandy”,”Stovall",
"Matthew T.”,”Strickland",
"Robert”,”Suggs",
"William”,”Sulik",
“Sullivan, Burd, Roupas & Wright",
"Brian R.”,”Summers",
"Barton”,”Swarr",
"Alan B.”,”Sykes",
"James”,”Taylor",
"Keith”,”Taylor",
"David”,”Galatas”,”Fayetteville Family Dentistry”,
"Jerry”,”ter Avest",
"Harry”,”Thomas",
"Paul”,”Thomas",
"Philip W.”,”Thomas",
"Dale”,”Thompson",
"James”,”Thompson",
"Sandra”,”Thore",
"Doris K.”,”Thorne",
"Todd”,”Tibbs",
"Todd”,”Sninski & Matt Schmitt”,”Raleigh”,
“Toe River Childrens Dental Clinin",
"Chris”,”Tope",
"Michael”,”Touloupas & Cynthia Touloupas",
“Commwell Health",
"Jason”,”Troutman",
"Charles W.Deceased”,”Tulloch & Dr. Gregory G. Manning",
"Daniel R.”,”Turnbull",
"Vic”,”Turner & Dr. Kirk Wilkie”,”Cary”,
"Cynthia”,”Tyson",
"Johannah”,”Tyson",
"Leo”,”Uicker",
“UNAVAILABLE",
“UNC Hospital”,”Dental Clinic”,
“UNC School of Dentistry”,”Dental Research”,
“UNC School of Dentistry”,”Generalist”,
“UNC School of Dentistry”,”Oral Surgery”,
“UNC School of Dentistry”,”Periodontology”,
"Nash”,”Underwood",
“Union County Health Department",
“University Dental Associates”,”CN”,
“University Dental Associates”,”Creedmoor”,
“University Dental Associates”,”Crown Point”,
“University Dental Associates”,”Durham”,
“University Dental Associates”,”Interchange”,
“University Dental Associates”,”Ortho”,
“University Dental Associates”,”Preston”,
“University Dental Associates”,”South Park”,
“University Dental Associates”,”University”,
“University Dental Associates”,”Waverly”,
"Gerald”,”Upton",
"Kevin”,”Upton",
"John”,”Van Venrooy",
"Stephen J.”,”Vanyo",
"Thomas”,”Vaughan",
"Carlos”,”Velez",
"Scott”,”Via",
"Tom”,”Vicars",
"Dinah”,”Vice”,”Chapel Hill”,
"Dinah”,”Vice”,”Sunrise Dental”,
"Gabriel”,”Villena",
"Dwight deceased”,”Vincent",
"Rosanie”,”Voegele",
"Henry”,”Vruwink",
"Joel”,”Wagoner",
"Bruce”,”Wainright",
“Wake County Human Services”,”Dental Health”,
“Wake Health Service”,”New Bern Ridge”,
"Cindy”,”Walker",
"Michael”,”Tapper",
"Renee”,”Wall",
"Russell”,”Walton",
"George”,”Ward",
"John”,”Wardsworth",
"Otis”,”Washington",
"Steve”,”Watson",
“Wayne County Health Department",
"Howard”,”Weeks",
"Neil”,”Welborne",
"Gary”,”Weller",
"James”,”Wells",
"James A.”,”Wells",
"Jeffrey”,”West",
"Millard”,”Wester",
"Dan”,”Wheless",
"Stephen”,”White",
"Jeff sold to  Lane”,”Whitehead",
"Seth C.”,”Rumley, DDS, PA",
"James A.”,”Whitley",
"Don”,”Whitworth",
"Lynn”,”Wiggs",
"Batchelor”,”William",
"A. C.”,”Williams",
"David”,”Williams",
"J. Michael”,”Williams",
"Larry A.”,”Williams",
"Craig”,”Williams",
"Paul”,”Manning",
"Robert”,”Williamson”,”Cameron Village”,
"Charles”,”Willis",
"Michael”,”Willock",
"Brian”,”Willson",
"Jim”,”Wilson",
"Matthew”,”Wirick”,”Community Dental”,
"Carter”,”Wiseman",
"Julie”,”Witte",
"John”,”Woodall",
"Michael”,”Woodard",
"Ernest”,”Wooden",
"James”,”Woodford",
"Donna”,”Woodruff",
"Jean”,”Woods",
"William”,”Wooten",
"William”,”Wynne",
"Valerie”,”Wynne-Hall",
"Steve”,”Yang",
"John deceased”,”Yeager",
"Merlin”,”Young",
"Scott”,”Young",
"Efrain”,”Zambrana",
"Julia”,”Zervos & Dr. Amy Banks Earwood",
"Mark”,”Zurawel",
"Allan”,”Acton”,”Cary Family Dental”,
"Douglas”,”Yauch",
"Darryl”,”Warren",
"John”,”Powell”,”Weldon”,
“NC State Board of Dental Examiners",
“Twin County Rural Health Center”,”Jackson”,
“Knight & Malek”,”Axiom of Little Village”,
“Rockingham County Department of Public Health",
"David”,”Hoyle",
"Mark”,”Barrett & Dr. Kevin Collins",
"Melissa”,”Davidian",
"Shailesh”,”Patel",
"Gregory”,”Manning",
"Karen”,”Petty",
"Amit V.”,”Patel",
“Howarth Family Dental Center”,”Cary”,
"Herbert”,”Hudson",
“Stanly County Health Dept.",
"Charles”,”Disdier”,”Wilson”,
"Bilal”,”Saib",
"James”,”Green",
"Numa”,”Cobb",
"Alison”,”Lohman & Dr. Annu Sood",
"Eric”,”Davis",
"Kyle J.”,”Roth”,”Durham”,
"William”,”Tripp",
"Walter”,”Scott”,”Owens  Drive”,
"James”,”Haynes",
"Jennifer”,”Le",
"John M.”,”Hall",
“Davidian & Associates",
"Stewart”,”Wignall",
“Vance Warren Comprehensive Health Plan",
"Roger”,”Urlaub",
"Timothy”,”Scheetz",
“Columbus County Health Department",
"Richard”,”Carlyle",
"Thomas”,”Fleming",
"Kenneth”,”Diehl",
"Cynthia”,”Pratt",
"Katherine”,”Garrett",
"Robert B.”,”Allen",
"Paul”,”Watkins",
"Paul”,”Watkins”,”Greenville”,
"Richard”,”Anglin",
“Smithfield Family Dentistry",
“Dental Care Center”,”HHMW1-Greenville”,
"Edward”,”Altherr",
"Waka”,”Kadoma",
"Jason”,”Pate",
"Brent”,”Lawson",
"James H”,”Wells",
"Hushang”,”Ghodrat”,”Willowdaile Family”,
“Immigrant Health Initiative Chatham Hosp",
"Andrew”,”Rudd",
"Edward”,”Scammon",
"Edward”,”Scammon”,”Raeford”,
"Thomas J.”,”Griffin",
"Angela”,”Wingate",
"Kyle J.”,”Roth”,”Sanford”,
"Jeffery”,”Jelic",
“Lane and Associates”,”Sanford/Tiffany”,
"James”,”Musselwhite",
"James”,”White",
"Kim”,”Melton",
"Jonathan”,”Beavers",
"Anna”,”Goodrich”,”Moore County Dental”,
“Knowles, Smith, & Assoc.”,”2029 Valley Gate Dr.”,
"Frank”,”Ausband",
"Susan”,”Banta",
"Robert”,”Chandler",
"Charles”,”Allen",
"Maja”,”Martin",
"Jeff”,”Reintgen”,”Apex”,
"Miller”,”Gibbons",
"Peter”,”Tzendzalian",
“Wayne Community College",
"Hiren”,”Patel",
"Ema”,”Chohan",
“Alamance Community College",
“Cape Fear Community College",
“Central Piedmont Community College",
"Francis”,”Amato",
“Coastal Carolina Community College",
“Fayetteville Technical Community College",
“Guilford Technical Community College",
“UNC Dental School",
"Natalie B.”,”McCarthy",
"Timothy D.”,”Sims",
"Joseph”,”Barber",
"Timothy”,”Naomi",
"Gary”,”Cameron",
"Larry”,”Moray”,”Chapel Hill”,
"Gregory”,”Weaver",
"Mary”,”Walton",
“Dental Works”,”Greensboro #104”,
"John”,”Pfefferle",
"Charles”,”Simpson",
"Robert”,”Williamson”,”Princeton”,
“Person County Health Dept.",
"Tyson”,”Roe",
"Farzana A.”,”Rahman”,”Triangle Orthodontics”,
"Renate”,”Soltmann",
"Dan”,”Shield",
"William C.”,”Windley III",
"Sandra”,”Doonquah",
"Jim”,”Tate”,”Mens Baptist Bus”,
"Douglas”,”Fowler",
"Jennifer”,”Tedder",
"Gordon”,”Leden",
“Huff and Huff, DDS, P.A.",
"William”,”Inge",
"Eric”,”Campbell”,”Campbell Orthodontics”,
"Philip A.”,”Lisk",
"Paul”,”Watkins”,”Winston Salem”,
“Correct Care Solutions”,”Dur Co Detention”,
“Palp",
"Sharon”,”Cobham”,”Apex”,
"Jenny”,”Babinec",
“Wake AHEC",
"Manoj B”,”Patel",
"Michael”,”Riccobene”,”Garner 4042”,
"Himi”,”Saxena",
"Joseph”,”Mooring”,”Retired”,
"Joyce”,”Guanga",
"John”,”Ceraso",
“Lane and Associates”,”Durham”,
"Don”,”Lane”,”Greensboro”,
“Hoffman & Arthur, DDS PA",
“Lane and Associates”,”Harvest Oaks”,
“Lane and Associates”,”Wake Forest Rd”,
“Lane and Associates”,”Sanford/Horner”,
"Manoj B.”,”Patel",
"H. Reid”,”Hart",
"George”,”Zarb",
“Henderson Family Dentistry",
“N.C. Department of Corrections”,”Hoke County at McCain Hospital”,
“N.C. Department of Corrections”,”Craggy Creshold Facility Ashv”,
"Geeta”,”Bhat”,”Cary”,
"William S.”,”Wooten",
“ITC",
"Kyle”,”Roth”,”Goldsboro”,
"Marcia”,”Rementer”,”Chatham/Siler City”,
"Hushang”,”Ghodrat”,”Oxford”,
"Arun”,”Sharda & Associates",
“Dorothea Dix Hospital Dental Clinic",
"Edward”,”Wenda",
"Steven H.”,”Davis",
“Lane and Associates”,”Erwin”,
“Lane and Associates”,”Mount Olive”,
“Hlifax Community College",
“Halifax Community College",
"Robert”,”Jepko",
"Theodore”,”Roberson",
"Mercedes”,”Diaz",
“Electronic Data Systems”,”EDS”,
“Dental Care Center”,”HHMW2-Wilson”,
“Dental Works”,”Raleigh #111”,
"Sangita”,”Doshi",
"Deane”,”Hundley III",
"Doshi”,”Sangita",
"James”,”Harold",
"Jiger”,”Shah”,”Serene Smiles”,
"Patrick”,”Broome",
"Amy”,”See",
"Lane”,”Harris",
"Bruce”,”Howerton”,”Carolina OMF Imaging”,
“UNC”,”Faculty Practice”,
"Scott”,”Matthews",
"William”,”Kincaid",
"Ronald”,”Venezie",
“Murdoch Center",
"Macon”,”Sapp",
"Brent”,”Neidenthal”,” Sunset Ridge Family Dentistry”,
"Debora”,”Bolton”,”Willowdaile Family”,
“Piedmont Health Services”,”Carrboro”,
"Christopher”,”Koppelman",
“Carolina Family Health Center",
"Mike”,”Wilson”,”Durham”,
"Mike”,”Wilson”,”Oxford”,
"Michelle”,”Heffernan",
“Knight and Malek”,”Axiom of Zebulon”,
"Kenneth”,”Tripp",
“Marshall, King and Bassinger",
“Creedmoor Family Dentistry",
"Robert”,”Miller”,”New Bern”,
"Jerry”,”Bayliff",
"Robbie T.”,”Smith",
"Amin”,”Rahman",
"John”,”Won",
"Angela”,”Ellis",
"Todd W.”,”Garca",
"Todd W.”,”Garcia”,”“,
"Moses”,”Watson III”,”Raleigh”,
"Moses”,”Watson III”,”Laurinburg”,
"Mark”,”Pabst",
"Jamie”,”Understein”,”Dental Powers”,
"Deborah Ann”,”Conner",
"Veronica”,”Taylor-Williams",
"Christopher James”,”Clark",
“Lane and Associates”,”Garner”,
“You",
"Lawrence”,”Venet",
"Tracie”,”Vestal",
"D. H.”,”Taylor",
“Butner-Creedmoor Family Dentistry",
"Larry”,”Moray”,”Sanford”,
"Kenneth”,”Benson",
"Kyle”,”Roth”,”Burlington”,
"Karl”,”Pierce",
“Lane and Associates”,”Fayetteville”,
"Amy T.”,”Moubry",
"Janier”,”Barton",
“Dental Care Center”,”HHMW3-Fayetteville”,
"Francis”,”Cusumano”,”Garner”,
“Lane and Associates”,”Greensboro”,
"Mohamed”,”Mohamed",
"Mark F.”,”Kozacko",
"Santa”,”McKibbins",
"Matthew”,”Wirick”,”Wilmington”,
"Mark”,”Beavers",
“Lane and Associates”,”Angier Office”,
"Charles”,”Disdier”,”Goldsboro”,
"Todd”,”Bovenizer",
“Bladenboro Family Dentistry",
"Sapna”,”Chandra”,”Reflection Dental”,
“Pender County Health Dept",
"P. A.”,”Daniel",
“On Site Dental",
"Julien”,”Warren & Dr. Melinda Warren",
“Lee County Health Department”,”Dr. Jeffrey Love”,
"Malcom”,”Lewis”,”Baptist Mens Dental Bus”,
“Blumenberg",
"Kyle”,”Roth”,”Benson”,
"George”,”Sutton",
"Kevin”,”Aiken",
"Larry”,”Moray”,”Wake Forest”,
"Maham”,”Akhter",
"Felicia”,”Singletary",
“New Hanover County Health Dept.",
"Timothy and Maureen”,”Raczka”,”Alliance Dentistry”,
"Kirby”,”Ransom”,”Gibsonville”,
"John”,”Collins",
"Michele”,”Singer”,”Crosscreek Family Dentistry”,
“Fuquay Varina Baptist Church",
"Halley”,”White",
“Knowles, Smith  & Associates”,”Weiss”,
"Chris”,”Halper",
"Glynda”,”McConville",
"Dan  Phelps & Dr.  Lisa”,”Phelps",
"Karen”,”Shaw",
"Alessandra”,”Ritter",
“Knowles, Smith, & Associates”,”Dunn Road”,
“Knowles, Smith, & Associates”,”St. Pauls”,
“Knowles, Smith, & Associates”,”Hope Mills”,
"Kevin”,”Salek",
"Murriel”,”McKoy",
"Lynn”,”Hobin”,”North Raleigh Dental Care”,
“News and Observer",
"Craig”,”Mize",
“Division of Medical Assistance",
"Tara”,”Howell”,”Carolina Dental Care”,
"Gilbert”,”Montoya",
“Ghodrat”,”Creedmoor”,
"Hushang”,”Ghodrat”,”Creedmoor”,
"J. Stephen”,”Hoard",
"Debra”,”Zombek, DDS, P.A.”,”Clayton Smiles”,
"Larry”,”Moray”,”Rocky Mount”,
"Dan”,”Pender",
"Felicia D.”,”Singletary”,”Comprehensive Dental Center”,
“Dental Care Center”,”HHMW4-Smithfield”,
"Suman”,”Vidyarthi",
“Piedmont Health Services”,”Siler City”,
"Robert”,”Miller”,”Mebane Complete Dental Care”,
"Robert”,”Williamson”,”Midtown/North Hills”,
“Medical Mutual",
"Christopher H.”,”Koppelman",
"Monique”,”Hudson",
"Patrick”,”O Brien”,”Carolina Comfort Dental”,
"Gail”,”Belvett”,”Southpoint Family Dentisty”,
"Jesse”,”Lee",
"Paul”,”Richardson",
"Charles”,”Disdier”,”Kinston”,
"Ryan”,”Galligan",
"Clara P.”,”Davis”,”Open Wide Family Dentistry”,
"Biyi”,”Oremosu”,”The Smile Center”,
"Robert”,”Williamson”,”Willmington”,
“,”“Johnston Family Dentistry”,”“,
"JoAnn R.”,”Caracofe",
"Kyle J.”,”Roth”,”High Point”,
"Robert”,”Williamson”,”Boylan Avenue”,
"Michael”,”Riccobene”,”McGees Crossroads”,
“Baker & Baker DDS, PA",
"Hushang”,”Ghodrat”,”Henderson”,
"Nicole”,”Williams”,”Goldsboro Dental Arts”,
"Perry”,”Jeffries”,”Durham”,
“B B & T Assura",
"Josiah”,”Chen”,”Morrisville Family”,
"Thomas”,”Long”,”Raleigh Institute Aesthetic”,
“Mahley",
“Lane and Associates”,”Dunn/Erwin”,
"David”,”Waack",
“Pittsboro Family Dentistry",
"Todd”,”Grooms”,”Alamance Pediatric Dentistry”,
“Haywood County Health Department",
"J. Mark”,”Oliver”,”High Point”,
"Nigel”,”Morgan",
"Britt”,”Vinson",
"Bert Warren and Dr. Jason”,”Hardee",
"Jeff”,”Calamos & Dr. Patrick Marsh”,”Clayton”,
“NC Department of Labor",
“Rutherford County Health Dept",
“Goshen Dental Services”,”Wallace”,
"Anil”,”Mathew",
“Catawba Valley Community College”,”CVCC”,
"Tamara”,”Evans",
"Ryan”,”Whalen",
“Toe River Childrens Dental Clinic",
"Deborah”,”Broyles",
"Vinod”,”Mathew",
"Daniel”,”Mahar",
"Sue”,”Fowler",
"Christopher”,”Clark”,”Clinton Office”,
"Morris H.”,”Griffin",
"Annelise”,”Hardin”,”Southern Village)”,
"Jack”,”Boone",
"Edward C.”,”Monroe",
"Jane”,”Quintana",
"Scott”,”Blanchard”,”Elizabeth City”,
"Scott”,”Blanchard”,”Nags Head”,
"Walter”,”Scott”,”Crosscreek Mall”,
"Lacey E.”,”Gane",
"Anthony”,”Horalek",
"R. Anthony”,”Murray",
“Lee",
"Meredith”,”Taylor",
"Leah”,”Beavers",
"Christopher”,”Clark”,”Leland”,
"Robert”,”Grzybowski”,”Great Lakes Dental”,
“Choe",
"Ben”,”Britt",
“Harmony Dental",
"William”,”Tapp",
"Bert Warren & Jason”,”Hardee",
"Patrick”,”Roberson",
“Treman and Treman",
"Arun”,”Sharda”,”Eden”,
"Katina Pittman and Dr. Dustin”,”Durden”,”McCrimmon Family”,
"J. Mark”,”Oliver”,”Winston Salem”,
"Mohamed”,”Mohamed”,”Henderson Paradise Family 1”,
"Michael”,”Riccobene”,”Flowers Plantation”,
"Joseph”,”Stark",
"Michael”,”Riccobene”,”Knightdale”,
"C. B”,”Smith, III",
“Dental Works”,”Wilmington # 113”,
"Saeed Momen”,”Mehrabani",
"J. Dempsey”,”Smith",
“Open Door Clinc",
“Dental Staffing of the Carolinas",
“NC Department of Revenue”,”Privelege License”,
“NC Dept. of Revenue",
"Valerie”,”Pollock",
"Marjan”,”Alvand”,”Capital Dental Care”,
"Lisa”,”Stoner",
"Todd”,”Sninski & Dr. Matt Schmitt”,”Roseboro Family Dentistry”,
"David”,”Boaz",
“Anson Regional Medical Services",
"Robert”,”Hoyle",
"Eric”,”Davis”,”Hillsborough”,
"David E.”,”Hoyle",
“NC  Dental U",
"Marcia”,”Rementer”,”Burlington”,
"Kelly”,”Wright",
“Eastern Carolina Medical Service",
"Steven”,”Airey”,”Appalachian Dental Care”,
"Mary Lynn”,”King",
"Dinah”,”Vice”,”Durham”,
"Meena”,”Chelury”,”Amberly Family Dentistry”,
"Ken”,”Harrell",
"Adam”,”Saunders",
"Debra”,”Zombek & Associates, DDS, P.A.",
"Rodrick”,”Alston",
"George”,”Jones",
"Shelly”,”Soch",
"Eve”,”Brown",
“Reach Out America”,”Dental Assistants”,
“Reach Out America”,”Dentist”,
"Beverly”,”Thurmond",
"Peter”,”Lim",
“Central Carolina Community College",
"Dr. Laura”,”Davillia & Dr. Norberto Velasquez",
"Kevin”,”Burton",
"Brett”,”Wells",
"James”,”Nelson",
"Charissa”,”Chin",
"Keisha R.”,”Brown”,”Something To Smile About”,
“Knowles, Smith and Associates”,”Eastover”,
“Bill",
“Melissa",
“Roberson Family Dentistry",
“schmidt",
"Todd”,”Sninski & Dr. Matt Schmitt, DMD, P.A.”,”Cary”,
"Sam”,”DeAngelo",
"Perry”,”Jeffries”,”Raleigh”,
"Kyle”,”Roth”,”Raleigh”,
"Vic”,”Turner & Dr. Kirk Wilkie”,”Raleigh”,
“Lane and Associates”,”Renaissance”,
“Dental Works”,”Winston Salem # 109”,
“Person Family Dental Center”,”Yanceyville”,
"Robert”,”Eisberg”,”Atlantic Family Dental”,
"Giles”,”Willis",
“Capps, Bowman, & Associates”,”Arlington Blvd”,
“Lane and Associates”,”Miami”,
“Dental Works”,”Wake Forest #120”,
"Brandy”,”Joyner and Dr. Kenisha Grant”,”Horizon Family Dentistry”,
"Amy”,”Kimes",
“Dental Works{Southpoint #121}",
"S. D.”,”Taylor",
"Kevin”,”Matthews",
"Simon”,”Melcher”,”Implant & General Dentistry”,
“Aoex Family Dental Care",
"Kavita”,”Ghai”,”Crescent Family Dentistry”,
"Howard”,”Yee”,”Louisburg”,
"Tina”,”Gupta”,”Smile Studio of North Raleigh”,
“Yadkin County Health Department",
“ACC Dental Consultants",
"Gerald”,”Coates”,”Stonebridge Dental Associates”,
"Marcus”,”Heyder",
“Dental Care Center”,”HHMW5-Durham”,
"Eric”,”Steinbicker",
"David”,”Dillard”,”Wake Cross Roads Dentistry”,
"Frank”,”Saas",
"Hakeem”,”Abdul-Karim",
"Uda”,”Reebye”,”Triangle Implant Center.”,
"Antonio”,”Braithwaite”,”Sanford Pediatric”,
“Roxboro Family Dentistry",
“Lane and Associates”,”Winston Salem”,
“Dental Works”,”Fayetteville #118”,
"Christopher”,”Clark”,”Zebulon”,
"Geeta”,”Bhat & Associates”,”Pinehurst”,
"Jill”,”Sonner”,”Renaissance Dental Center”,
“Lane and Associates”,”A Corporate”,
"Kyle”,”Roth & Associates”,”Carolina Dental Arts Greensbor”,
"Sharon”,”Cobham & Assoc”,”Anne Elizabeth Family Dental C”,
"Kyle”,”Roth”,”Greesnboro Dental Arts”,
"Kyle”,”Roth & Associates”,”Greensboro Dental Arts”,
“Denture Makers 2",
"Robert”,”Williamson”,”Smithfield Comprensive Dentist”,
"Bryden”,”McCormick",
"Jennifer M.”,”LaQuay",
"Dan”,”Davis Jr.”,”Smile Etcetera”,
"Edward”,”Jernigan",
“First Health Dental Care Centers",
"Tracie”,”Legette”,”College Lakes Family Dentistry”,
"J.Selig”,”Cooper",
"Cletus Helms  {Bunn Famiy Dentistry}”,”Simpson",
“Mobile Dentist",
"Amy”,”Watson",
"Richard”,”Godfrey",
"Dana”,”Shumate",
"Zara”,”Hernandez",
"Lisa”,”Powell",
"Seann”,”Meltzer”,”Butner-Creedmoor Family Dentis”,
"Ngozika”,”Daka DMD PA”,”Ferncreek Dental”,
"Hamid”,”Rouhani”,”Bright Smiles of Garner Family”,
"Zhanying”,”Guo",
“Lane and Associates”,”Surgical Suite”,
“Lane and Associates”,”Greenlevel”,
"Hesham”,”Baky & Dr. Jonathan Boes”,”Triangle Family Dentistry”,
“Lane and Associates”,”Ridge Road”,
"Jeffrey”,”Caldwell",
"Ken”,”Leahy”,”Leahy Family Dentistry”,
"Charles Steadman”,”Willis III",
"David”,”Galatas”,”Cameron”,
"Andrew Collins & Pedro”,”Santiago”,”Roxboro”,
"Andrew Collins & Pedro”,”Santiago”,”Durham”,
"Margaret”,”Montilus”,”Sterling Dental Care”,
"Zhanying”,”Li",
"Mohamed”,”Mohamed”,”Durham Paradise Family 3”,
“Dental Works”,”Highpoint #117”,
"Andrew”,”Farrell",
"Jean”,”Joh",
"William Ko & Dr. Mark”,”Pcolinsky”,”Smiles of Carolina”,
“Dental Works”,”Burlington #124”,
"Lisal”,”Isaacs",
“Pretzer & Kornstein”,”Wake Pediatrics Garner”,
"Tegran O.”,”Fraites”,”Angier Dental”,
“Dental Works”,”Corporate”,
"Karen”,”Torres",
"Linda”,”Levin",
"Craig”,”Winkelmann”,”Wake Forest Dental Arts”,
“Fuller and Associates”,”Reflections Dental”,
"Francis”,”Cusumano”,”Cary”,
"Ted”,”Mayer”,”(private)”,
"Kyle”,”Roth”,”Carolina Dental Arts”,
"Sidharth”,”Bansal”,”“,
"Ryan”,”Burleson",
"Meit”,”See",
"Michael”,”Brenegan",
"Armin”,”Abron”,”Chapel Hill”,
"Tracy”,”Waters",
“Dental Works”,”Lexington #112”,
"Jenine Giles & Dr. Tara”,”Wiggins”,”Main Street Family Dentistry”,
"Gary Jones, &  Dr. Gerald”,”Beatty",
“Dentistry Delivery",
"Calvin”,”Fuller",
"Fred”,”Keyser”,”Chapel Hill”,
"Christopher”,”Clark”,”Brier Creek”,
"Adam”,”Moore",
"Marcus”,”Curry",
"Tina”,”Gupta”,”Henderson”,
"Joseph”,”Yu”,”Stonebridge Dental Car”,
"Helen”,”Zhang",
"C. Andrew”,”Lee",
“Dental Works”,”Greenville #123”,
"Laurence”,”Mester",
"Arash”,”Bassiri”,”Good Middling Drive”,
"Jin Yi”,”Kwon”,”Urban Oasis Dental”,
“Greene County Health Care”,”JD Bernstein Dental Services”,
"Dani”,”Stansell",
"Amy”,”Gadol",
"Maura”,”Partrick",
"George S.”,”Dirani",
“Denture Makers 1",
"Jacqueline Garner and Dr. Ralph”,”Mensah”,”Integrated Dentistry”,
“Cobham (Durham Family Dentistry)",
“Dental Works”,”Greensboro/Wendover #122”,
"J. Gina”,”Lee”,”Brier Creek Ortho”,
"Hesham”,”Baky & Dr. Jonathan Boes”,”Wake Forest”,
"Robert”,”Kent",
“Dental Works”,”Leland”,
"Nicole”,”Le Cann, DDS PA”,”Raleigh”,
"Seema”,”Thaker",
"Kevin”,”Atkins”,”Chapel Hill”,
"Bill”,”Gates",
"Rick”,”Booth",
"Aaron”,”Hewett”,”Carolina Family Dentistry”,
"William R.”,”Warren",
"Lucas”,”Nazario",
"Bertrand”,”Bonnick",
"Vanessa M”,”Campbell",
“Rural Health Group”,”Jackson”,
"Michael”,”Riccobene”,”Wakefield”,
"Michael”,”Riccobene”,”Cary”,
“Dental Care Center”,”HHMW6-Wake Forest”,
"Patrice”,”Barber”,”Alliance Family Dental”,
"Jesse”,”Arbon",
“Rural Health Group”,”Roanoke Rapids”,
“Smiles of America”,”Charlotte”,
"Gordon L.”,”Townsend",
"Kenneth”,”Evins",
“Earp & Gamboa",
"Ken”,”Meeker & Associate”,”Kinston Dental Care Center”,
"Nicole”,”Williams”,”Raleigh”,
"Blake N.”,”Helmer",
"Dalton”,”Brooks",
"Brian”,”Pressley”,”Premier Dentistry”,
“Patel, Scott & Yee, PLLC”,”( All Smiles Dentistry}”,
"Carmen”,”Leary",
"Sharon”,”Cobham”,”Greensboro”,
"Steven E.”,”Garrett",
"Penelope”,”Kline",
"Steven”,”Van Scoyoc",
"Thomas N.”,”Pezdek",
"Thomas Joseph”,”Horton",
“Agape Health Clinic",
"Christopher”,”Clark”,”Mini City”,
"Ruma”,”Simhan",
"Deborah”,”Barson",
"Jake”,”Reynolds DMD MSD",
“Elite Dental Temps",
"Siti A.”,”Lowery",
"Jennifer”,”Bell & Dr. Angelina Marcil”,”Signature Family Dental”,
“Miller -Motte”,”Greenville”,
"Kyle”,”Roth”,”Falls of Neuse”,
“Oral & Maxillofacial Surgery Associates”,”Chapel Hill”,
“Oral MaxillofacialSurgery Associates”,”Sanford”,
"Kavita”,”Ghai”,”Cresent Dental Raleigh”,
"Rhonda”,”Kearney",
"Angelina”,”Marcil”,”Signature Family Dentistry”,
"Tony”,”Khara",
"Anthony”,”DeStefano",
"Uda”,”Reebye”,”(Triangle Implant Center-Meban”,
"Jin”,”kwon",
"Artimus”,”Brown",
"Larry”,”Moray”,”Burgaw”,
"Lindsey”,”Williams”,”Urban Oasis of Clayton”,
"Nathan & Shannon”,”French",
"Paul E.”,”Coggins",
"Sharon”,”Cobham”,”Winston Salem”,
"Kyle”,”Roth”,”Grave Dr. Goldsboro”,
"Christi”,”Davis”,”Capital City Pediatric Dentist”,
"Robert”,”Kent”,”Brier Creek”,
“Miller-Motte College”,”Raleigh”,
“Lane and Associates”,”Ortho”,
"James”,”Corcoran",
"Bikram”,”Singh",
"L. Daniel”,”Balance",
"Nikki”,”Tucker  & Dr. Shanetta Allen Johnson”,”Smile Junction”,
"Darryl”,”Diefes",
"Hesham”,”Baky & Dr. Jonathan Boes”,”FV Triangle Family Dentistry”,
"Christopher”,”Clark”,”Leesville Dental Care”,
“Samaritan Health Center",
"Ronald”,”Katz",
"Wendy”,”Britt",
"Farzana”,”Rahman”,”Raleigh Triangle Orthodontics”,
"Migule”,”Gonzalez",
"John”,”Walsh”,”Dentistry of the Carolinas”,
"Joseph”,”Kerner",
"Bryden”,”McCormick”,”Middle Creek”,
"Keenon L.”,”Johnson",
"James Crenshaw & William”,”Haight",
"Reginald”,”Baker”,”“,
"Eva”,”Ku",
"Gail”,”Belvett & Assoc. PA”,”Mebane Childrens Dentistry”,
"Kennard”,”Lloyd",
"Jeffrey”,”Almony, MD, DDS",
"Roslyn”,”Crisp”,”Church St”,
"Nicole”,”Le Cann, DDS PA”,”Apex”,
"Craig”,”Dorion",
"Linda”,”Shafik”,”St. Marys Office Family Dentis”,
"Chintan”,”Patel",
"Larry”,”Moray”,”Durham/Ortho”,
"Christine D.”,”Laster",
"Larry”,”Moray”,”Chapel  Hill/Ortho”,
"Mohamed”,”Mohamed”,”Greensboro Paradise Fami”,
"Tony”,”Khara”,”(Holly Springs)”,
"Kyle”,”Roth”,”Henderson”,
"Kamran”,”Qureshy”,”Cary Dental Center”,
"Mohamed”,”Mohamed”,”Greenville Smiles”,
"Rolando”,”Prado",
“Pollk Correctional Institution",
“Poke Correctional Institution",
"Stephanie”,”Conlan",
"Cole”,”Younger”,”Leesville Dental Care”,
"Richard C.”,”Adams",
"Brian”,”McManus",
“Lane and Associates”,”Roseboro”,
"Katayoun”,”Sadri",
"Tao”,”Gao",
"Theodore”,”Abraha”,”Abraha Family Dentistry”,
“Total Smiles of Durham",
"Yiping”,”Fang",
"Kyle”,”Roth”,”Creedmoor”,
“Department of Community Development”,”Durham”,
"Linda”,”Swain",
"Paula”,”Stapleton",
"Gaylia”,”Smith",
"Michael”,”Riccobene”,”Raleigh”,
"Ashley”,”Lloyd",
"T. Harold”,”Lancaster",
"Emily”,”Dornblazer",
“Commwell Health”,”(Four Oaks)”,
“UNC Hospital”,”Main”,
"Robert”,”Eisberg”,”(Garner) Atlantic Family Denta”,
"Hamid”,”Rouhani”,”Raleigh”,
"Joy”,”Graves”,”Oasis Dental”,
"Robert”,”Bailey”,”Access Family dental care”,
“Downtown Dental",
"Danielle”,”English",
“Dental Works”,”Salisbury”,
"Tasha”,”Hinton",
"Prasad”,”Vasamsetti",
"Larry”,”Moray”,”Mount Airy”,
"Ernest”,”Ward",
"Jason”,”Mullen”,”“,
"Tyler”,”Davis",
"Monica & Henry”,”Pierpan",
"Crystal”,”Rooks",
"Taylor”,”Edgerton",
"Julia”,”Tyson",
“Leland Family Dentistry",
"Robert”,”Loftin",
"Jyotica”,”Ahuja",
"Charles”,”Ferzli”,”NW Maynard”,
"Charles”,”Youngblade",
"Watson”,”Moses”,”Durham”,
"Moses”,”Watson III”,”Durham”,
"Walter”,”Futch",
"Boo”,”Lee”,”Blue Water Pediatric Dentistry”,
"Arun”,”Sharda”,”Greensboro”,
"Ryan”,”Staehling”,”Southern dental arts”,
"Allessandra”,”Lowery",
"Brian”,”Vinson",
"Sid”,”Pazokian",
"Robert Hollowell &  Dr Allen”,”Porter”,”Triangle Pediatric Dentistry”,
"Shanean”,”Anderson”,”Smiles Sculptures of Wake Fore”,
"William E.”,”Argersinger",
“Gurley, Ritter, & Brogden (Preston)",
“Gurley, Ritter, & Brogden (SW Cary)",
"Kyle”,”Roth”,”Morrisville”,
"Amy”,”Davidian”,”Southpoint Pediatric Dentistry”,
“New Hanovier Community Health Center",
"Jonathan Wang & Dr. Xuan”,”Tran”,”Carolina Smiles of Greensboro”,
"UDA”,”(wycliff)",
"Universal Dental Associates”,”(Wycliff)",
“University Dental Associates”,”Wycliff”,
"Bob”,”Means",
"Chuanwen”,”Sun",
"James”,”Furgurson",
“Knight and Malek”,”Axiom of Cary”,
"Donald”,”Brown and Associates  DDS, ,PLLC",
“,”“Lifepoint Church”,”“,
“,”“Lane and Associates”,”Knightdale”,
"Brian”,”Summers, & Dr. Patrick Johnson",
"Scott”,”McClure”,”Raleigh”,
"Scott”,”McClure”,”Garner”,
"Scott”,”McClure”,”Cary”,
"Kelly”,”Viau”

*/

];
	
    $( "#namefield" ).autocomplete({
      source: availableTags
    });
	
  });

